### ISSUE TITLE
Dynamic array mapping

### ISSUE THREAD

**Issue by corysimmons** [SamKnows/transform-when#5]
![image](https://user-images.githubusercontent.com/224636/34201692-53540dde-e543-11e7-8136-fc7652f8c629.png)

be a lot cooler if it were...

![image](https://user-images.githubusercontent.com/224636/34201721-67a12fc4-e543-11e7-8f38-0e8cccd47a44.png)

Similar to how css animations work.

**Comment by corysimmons** [comment]
I should also mention that the first screenshot is a bit janky. Particularly the first few frames of it scaling just jump a significant chunk of the transition... :\

**Comment by callumacrae** [comment]
Have you tried transformObj? I think it does what you're looking for, just with a slightly different syntax.

**Comment by corysimmons** [comment]
No. Will look into it.
